import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.scss";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../../public/Components/Header";

  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PortBIM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header/>
        <>
          {children}
        </>
        {/* <Script src="/js/jquery-1.11.2.js"></Script> */}
        {/* <Script src="/js/lottie-interactivity.min.js"></Script> */}
        {/* <Script src="/js/lottie-player.js"></Script> */}
        {/* <Script type="text/javascript" src="/js/ellipsify.min.js"></Script> */}
        {/* <Script src="/js/slick.min.js"></Script> */}
        {/* <Script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></Script> */}
        {/* <Script src="/js/JQFunctions.js"></Script> */}


      </body>
    </html>
  );
}
